language: python
sudo: false
cache: pip

before_install:
  - sudo apt-get install libpoppler-cpp-dev libxml2-dev libxslt-dev

python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install 'requests>=2.21.0'
  - pip install 'habanero>=0.6.2'
  - pip install 'pdftotext>=2.1.1'
  - pip install 'lxml>=4.2.5'
  - pip install vcrpy

script:
  - nosetests -v --cover-package=pyminer
