language: python
sudo: false
cache: pip

before_install:
  - sudo apt-get install libpoppler-cpp-dev libxml2-dev libxslt-dev

python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest --verbose
